from __main__ import qt, ctk

from iGyneStep import *
from Helper import *
from iGyneUI import *
import PythonQt

class iGyneSelectProcedureStep( iGyneStep ) :

  def __init__( self, stepid ):
    self.initialize( stepid )
    self.setName( '1. Select the Procedure' )
    self.setDescription( 'Select the procedure used in this iGyne case.' )
    self.__parent = super( iGyneSelectProcedureStep, self )

  def createUserInterface( self ):
    '''
    '''

    self.__layout = self.__parent.createUserInterface()
    TemplateSheetWidget = qt.QWidget()
    self.setupUi(TemplateSheetWidget)
    
  def onEntry(self, comingFrom, transitionType):

    super(iGyneSelectProcedureStep, self).onEntry(comingFrom, transitionType)
    pNode = self.parameterNode()
    pNode.SetParameter('currentStep', self.stepid)
    # self.updateWidgetFromParameterNode(pNode)    
    # qt.QTimer.singleShot(0, self.killButton)

  def onExit(self, goingTo, transitionType):

    super(iGyneSelectProcedureStep, self).onExit(goingTo, transitionType) 

  # def updateWidgetFromParameters(self, parameterNode):

     # procedure = parameterNode.GetParameter('procedure')

  def validate( self, desiredBranchId ):
    '''
    '''
    self.__parent.validate( desiredBranchId )    
    self.__parent.validationSucceeded(desiredBranchId)
   
###############################################################################
#################################################################################

  def setupUi(self, TemplateSheetWidget):
    TemplateSheetWidget.setObjectName(("TemplateSheetWidget"))
    TemplateSheetWidget.resize(552, 682)
    self.label = qt.QLabel(TemplateSheetWidget)
    self.label.setEnabled(True)
    self.label.setGeometry(qt.QRect(5, 52, 541, 625))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Preferred, qt.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
    self.label.setSizePolicy(sizePolicy)
    self.label.setText((""))
    self.label.setPixmap(qt.QPixmap((":/Icons/GyneSheetVert.png")))
    self.label.setObjectName(("label"))
    self.CqColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CqColorPushButton.setEnabled(True)
    self.CqColorPushButton.setGeometry(qt.QRect(174, 185, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CqColorPushButton.sizePolicy().hasHeightForWidth())
    self.CqColorPushButton.setSizePolicy(sizePolicy)
    self.CqColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CqColorPushButton.setObjectName(("CqColorPushButton"))
    self.CpRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CpRadioButton.setEnabled(True)
    self.CpRadioButton.setGeometry(qt.QRect(128, 247, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CpRadioButton.sizePolicy().hasHeightForWidth())
    self.CpRadioButton.setSizePolicy(sizePolicy)
    self.CpRadioButton.setText((""))
    self.CpRadioButton.setAutoExclusive(False)
    self.CpRadioButton.setObjectName(("CpRadioButton"))
    self.CpColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CpColorPushButton.setEnabled(True)
    self.CpColorPushButton.setGeometry(qt.QRect(123, 225, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CpColorPushButton.sizePolicy().hasHeightForWidth())
    self.CpColorPushButton.setSizePolicy(sizePolicy)
    self.CpColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CpColorPushButton.setObjectName(("CpColorPushButton"))
    self.CqRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CqRadioButton.setEnabled(True)
    self.CqRadioButton.setGeometry(qt.QRect(177, 208, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CqRadioButton.sizePolicy().hasHeightForWidth())
    self.CqRadioButton.setSizePolicy(sizePolicy)
    self.CqRadioButton.setText((""))
    self.CqRadioButton.setAutoExclusive(False)
    self.CqRadioButton.setObjectName(("CqRadioButton"))
    self.CrColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CrColorPushButton.setEnabled(True)
    self.CrColorPushButton.setGeometry(qt.QRect(231, 165, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CrColorPushButton.sizePolicy().hasHeightForWidth())
    self.CrColorPushButton.setSizePolicy(sizePolicy)
    self.CrColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CrColorPushButton.setObjectName(("CrColorPushButton"))
    self.CrRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CrRadioButton.setEnabled(True)
    self.CrRadioButton.setGeometry(qt.QRect(235, 187, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CrRadioButton.sizePolicy().hasHeightForWidth())
    self.CrRadioButton.setSizePolicy(sizePolicy)
    self.CrRadioButton.setText((""))
    self.CrRadioButton.setAutoExclusive(False)
    self.CrRadioButton.setObjectName(("CrRadioButton"))
    self.horizontalLayoutWidget = qt.QWidget(TemplateSheetWidget)
    self.horizontalLayoutWidget.setEnabled(True)
    self.horizontalLayoutWidget.setGeometry(qt.QRect(5, 6, 538, 36))
    self.horizontalLayoutWidget.setObjectName(("horizontalLayoutWidget"))
    self.horizontalLayout = qt.QHBoxLayout(self.horizontalLayoutWidget)
    self.horizontalLayout.setMargin(0)
    self.horizontalLayout.setObjectName(("horizontalLayout"))
    self.LoadTemplatePushButton = qt.QPushButton(self.horizontalLayoutWidget)
    self.LoadTemplatePushButton.setEnabled(True)
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Preferred, qt.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.LoadTemplatePushButton.sizePolicy().hasHeightForWidth())
    self.LoadTemplatePushButton.setSizePolicy(sizePolicy)
    self.LoadTemplatePushButton.setObjectName(("LoadTemplatePushButton"))
    self.horizontalLayout.addWidget(self.LoadTemplatePushButton)
    self.AddVolumePushButton = qt.QPushButton(self.horizontalLayoutWidget)
    self.AddVolumePushButton.setEnabled(True)
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Preferred, qt.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AddVolumePushButton.sizePolicy().hasHeightForWidth())
    self.AddVolumePushButton.setSizePolicy(sizePolicy)
    self.AddVolumePushButton.setObjectName(("AddVolumePushButton"))
    self.horizontalLayout.addWidget(self.AddVolumePushButton)
    self.ShowNeedlesPushButton = qt.QPushButton(self.horizontalLayoutWidget)
    self.ShowNeedlesPushButton.setEnabled(True)
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Preferred, qt.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.ShowNeedlesPushButton.sizePolicy().hasHeightForWidth())
    self.ShowNeedlesPushButton.setSizePolicy(sizePolicy)
    self.ShowNeedlesPushButton.setCheckable(True)
    self.ShowNeedlesPushButton.setChecked(False)
    self.ShowNeedlesPushButton.setObjectName(("ShowNeedlesPushButton"))
    self.horizontalLayout.addWidget(self.ShowNeedlesPushButton)
    self.SelectNeedlesPushButton = qt.QPushButton(self.horizontalLayoutWidget)
    self.SelectNeedlesPushButton.setEnabled(True)
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Preferred, qt.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.SelectNeedlesPushButton.sizePolicy().hasHeightForWidth())
    self.SelectNeedlesPushButton.setSizePolicy(sizePolicy)
    self.SelectNeedlesPushButton.setObjectName(("SelectNeedlesPushButton"))
    self.horizontalLayout.addWidget(self.SelectNeedlesPushButton)
    self.ObturatorSpinBox = qt.QSpinBox(self.horizontalLayoutWidget)
    self.ObturatorSpinBox.setEnabled(True)
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Preferred, qt.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.ObturatorSpinBox.sizePolicy().hasHeightForWidth())
    self.ObturatorSpinBox.setSizePolicy(sizePolicy)
    self.ObturatorSpinBox.setMinimum(-50)
    self.ObturatorSpinBox.setMaximum(50)
    self.ObturatorSpinBox.setObjectName(("ObturatorSpinBox"))
    self.horizontalLayout.addWidget(self.ObturatorSpinBox)
    self.CADmodel2ImageRegPushButton = qt.QPushButton(self.horizontalLayoutWidget)
    self.CADmodel2ImageRegPushButton.setEnabled(True)
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Preferred, qt.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CADmodel2ImageRegPushButton.sizePolicy().hasHeightForWidth())
    self.CADmodel2ImageRegPushButton.setSizePolicy(sizePolicy)
    self.CADmodel2ImageRegPushButton.setObjectName(("CADmodel2ImageRegPushButton"))
    self.horizontalLayout.addWidget(self.CADmodel2ImageRegPushButton)
    self.CaRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CaRadioButton.setEnabled(True)
    self.CaRadioButton.setGeometry(qt.QRect(299, 185, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CaRadioButton.sizePolicy().hasHeightForWidth())
    self.CaRadioButton.setSizePolicy(sizePolicy)
    self.CaRadioButton.setText((""))
    self.CaRadioButton.setAutoExclusive(False)
    self.CaRadioButton.setObjectName(("CaRadioButton"))
    self.CaColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CaColorPushButton.setEnabled(True)
    self.CaColorPushButton.setGeometry(qt.QRect(297, 165, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CaColorPushButton.sizePolicy().hasHeightForWidth())
    self.CaColorPushButton.setSizePolicy(sizePolicy)
    self.CaColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CaColorPushButton.setObjectName(("CaColorPushButton"))
    self.CbRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CbRadioButton.setEnabled(True)
    self.CbRadioButton.setGeometry(qt.QRect(362, 206, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CbRadioButton.sizePolicy().hasHeightForWidth())
    self.CbRadioButton.setSizePolicy(sizePolicy)
    self.CbRadioButton.setText((""))
    self.CbRadioButton.setAutoExclusive(False)
    self.CbRadioButton.setObjectName(("CbRadioButton"))
    self.CbColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CbColorPushButton.setEnabled(True)
    self.CbColorPushButton.setGeometry(qt.QRect(360, 184, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CbColorPushButton.sizePolicy().hasHeightForWidth())
    self.CbColorPushButton.setSizePolicy(sizePolicy)
    self.CbColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CbColorPushButton.setObjectName(("CbColorPushButton"))
    self.CcRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CcRadioButton.setEnabled(True)
    self.CcRadioButton.setGeometry(qt.QRect(410, 245, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CcRadioButton.sizePolicy().hasHeightForWidth())
    self.CcRadioButton.setSizePolicy(sizePolicy)
    self.CcRadioButton.setText((""))
    self.CcRadioButton.setAutoExclusive(False)
    self.CcRadioButton.setObjectName(("CcRadioButton"))
    self.CcColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CcColorPushButton.setEnabled(True)
    self.CcColorPushButton.setGeometry(qt.QRect(405, 225, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CcColorPushButton.sizePolicy().hasHeightForWidth())
    self.CcColorPushButton.setSizePolicy(sizePolicy)
    self.CcColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CcColorPushButton.setObjectName(("CcColorPushButton"))
    self.CdRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CdRadioButton.setEnabled(True)
    self.CdRadioButton.setGeometry(qt.QRect(443, 299, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CdRadioButton.sizePolicy().hasHeightForWidth())
    self.CdRadioButton.setSizePolicy(sizePolicy)
    self.CdRadioButton.setText((""))
    self.CdRadioButton.setAutoExclusive(False)
    self.CdRadioButton.setObjectName(("CdRadioButton"))
    self.CdColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CdColorPushButton.setEnabled(True)
    self.CdColorPushButton.setGeometry(qt.QRect(438, 277, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CdColorPushButton.sizePolicy().hasHeightForWidth())
    self.CdColorPushButton.setSizePolicy(sizePolicy)
    self.CdColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CdColorPushButton.setObjectName(("CdColorPushButton"))
    self.CeRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CeRadioButton.setEnabled(True)
    self.CeRadioButton.setGeometry(qt.QRect(455, 359, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CeRadioButton.sizePolicy().hasHeightForWidth())
    self.CeRadioButton.setSizePolicy(sizePolicy)
    self.CeRadioButton.setText((""))
    self.CeRadioButton.setAutoExclusive(False)
    self.CeRadioButton.setObjectName(("CeRadioButton"))
    self.CeColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CeColorPushButton.setEnabled(True)
    self.CeColorPushButton.setGeometry(qt.QRect(453, 337, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CeColorPushButton.sizePolicy().hasHeightForWidth())
    self.CeColorPushButton.setSizePolicy(sizePolicy)
    self.CeColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CeColorPushButton.setObjectName(("CeColorPushButton"))
    self.CfRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CfRadioButton.setEnabled(True)
    self.CfRadioButton.setGeometry(qt.QRect(443, 417, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CfRadioButton.sizePolicy().hasHeightForWidth())
    self.CfRadioButton.setSizePolicy(sizePolicy)
    self.CfRadioButton.setText((""))
    self.CfRadioButton.setAutoExclusive(False)
    self.CfRadioButton.setObjectName(("CfRadioButton"))
    self.CfColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CfColorPushButton.setEnabled(True)
    self.CfColorPushButton.setGeometry(qt.QRect(441, 393, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CfColorPushButton.sizePolicy().hasHeightForWidth())
    self.CfColorPushButton.setSizePolicy(sizePolicy)
    self.CfColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CfColorPushButton.setObjectName(("CfColorPushButton"))
    self.CgRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CgRadioButton.setEnabled(True)
    self.CgRadioButton.setGeometry(qt.QRect(410, 472, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CgRadioButton.sizePolicy().hasHeightForWidth())
    self.CgRadioButton.setSizePolicy(sizePolicy)
    self.CgRadioButton.setText((""))
    self.CgRadioButton.setAutoExclusive(False)
    self.CgRadioButton.setObjectName(("CgRadioButton"))
    self.CgColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CgColorPushButton.setEnabled(True)
    self.CgColorPushButton.setGeometry(qt.QRect(411, 447, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CgColorPushButton.sizePolicy().hasHeightForWidth())
    self.CgColorPushButton.setSizePolicy(sizePolicy)
    self.CgColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CgColorPushButton.setObjectName(("CgColorPushButton"))
    self.ChRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.ChRadioButton.setEnabled(True)
    self.ChRadioButton.setGeometry(qt.QRect(363, 511, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.ChRadioButton.sizePolicy().hasHeightForWidth())
    self.ChRadioButton.setSizePolicy(sizePolicy)
    self.ChRadioButton.setText((""))
    self.ChRadioButton.setAutoExclusive(False)
    self.ChRadioButton.setObjectName(("ChRadioButton"))
    self.ChColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.ChColorPushButton.setEnabled(True)
    self.ChColorPushButton.setGeometry(qt.QRect(360, 487, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.ChColorPushButton.sizePolicy().hasHeightForWidth())
    self.ChColorPushButton.setSizePolicy(sizePolicy)
    self.ChColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.ChColorPushButton.setObjectName(("ChColorPushButton"))
    self.CiRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CiRadioButton.setEnabled(True)
    self.CiRadioButton.setGeometry(qt.QRect(302, 533, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CiRadioButton.sizePolicy().hasHeightForWidth())
    self.CiRadioButton.setSizePolicy(sizePolicy)
    self.CiRadioButton.setText((""))
    self.CiRadioButton.setAutoExclusive(False)
    self.CiRadioButton.setObjectName(("CiRadioButton"))
    self.CiColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CiColorPushButton.setEnabled(True)
    self.CiColorPushButton.setGeometry(qt.QRect(297, 511, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CiColorPushButton.sizePolicy().hasHeightForWidth())
    self.CiColorPushButton.setSizePolicy(sizePolicy)
    self.CiColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CiColorPushButton.setObjectName(("CiColorPushButton"))
    self.CjRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CjRadioButton.setEnabled(True)
    self.CjRadioButton.setGeometry(qt.QRect(236, 533, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CjRadioButton.sizePolicy().hasHeightForWidth())
    self.CjRadioButton.setSizePolicy(sizePolicy)
    self.CjRadioButton.setText((""))
    self.CjRadioButton.setAutoExclusive(False)
    self.CjRadioButton.setObjectName(("CjRadioButton"))
    self.CjColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CjColorPushButton.setEnabled(True)
    self.CjColorPushButton.setGeometry(qt.QRect(234, 513, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CjColorPushButton.sizePolicy().hasHeightForWidth())
    self.CjColorPushButton.setSizePolicy(sizePolicy)
    self.CjColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CjColorPushButton.setObjectName(("CjColorPushButton"))
    self.CkRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CkRadioButton.setEnabled(True)
    self.CkRadioButton.setGeometry(qt.QRect(176, 514, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CkRadioButton.sizePolicy().hasHeightForWidth())
    self.CkRadioButton.setSizePolicy(sizePolicy)
    self.CkRadioButton.setText((""))
    self.CkRadioButton.setAutoExclusive(False)
    self.CkRadioButton.setObjectName(("CkRadioButton"))
    self.CkColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CkColorPushButton.setEnabled(True)
    self.CkColorPushButton.setGeometry(qt.QRect(177, 486, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CkColorPushButton.sizePolicy().hasHeightForWidth())
    self.CkColorPushButton.setSizePolicy(sizePolicy)
    self.CkColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CkColorPushButton.setObjectName(("CkColorPushButton"))
    self.ClRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.ClRadioButton.setEnabled(True)
    self.ClRadioButton.setGeometry(qt.QRect(128, 473, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.ClRadioButton.sizePolicy().hasHeightForWidth())
    self.ClRadioButton.setSizePolicy(sizePolicy)
    self.ClRadioButton.setText((""))
    self.ClRadioButton.setAutoExclusive(False)
    self.ClRadioButton.setObjectName(("ClRadioButton"))
    self.ClColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.ClColorPushButton.setEnabled(True)
    self.ClColorPushButton.setGeometry(qt.QRect(123, 456, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.ClColorPushButton.sizePolicy().hasHeightForWidth())
    self.ClColorPushButton.setSizePolicy(sizePolicy)
    self.ClColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.ClColorPushButton.setObjectName(("ClColorPushButton"))
    self.CmRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CmRadioButton.setEnabled(True)
    self.CmRadioButton.setGeometry(qt.QRect(95, 423, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CmRadioButton.sizePolicy().hasHeightForWidth())
    self.CmRadioButton.setSizePolicy(sizePolicy)
    self.CmRadioButton.setText((""))
    self.CmRadioButton.setAutoExclusive(False)
    self.CmRadioButton.setObjectName(("CmRadioButton"))
    self.CmColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CmColorPushButton.setEnabled(True)
    self.CmColorPushButton.setGeometry(qt.QRect(96, 402, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CmColorPushButton.sizePolicy().hasHeightForWidth())
    self.CmColorPushButton.setSizePolicy(sizePolicy)
    self.CmColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CmColorPushButton.setObjectName(("CmColorPushButton"))
    self.CnRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CnRadioButton.setEnabled(True)
    self.CnRadioButton.setGeometry(qt.QRect(86, 359, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CnRadioButton.sizePolicy().hasHeightForWidth())
    self.CnRadioButton.setSizePolicy(sizePolicy)
    self.CnRadioButton.setText((""))
    self.CnRadioButton.setAutoExclusive(False)
    self.CnRadioButton.setObjectName(("CnRadioButton"))
    self.CnColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CnColorPushButton.setEnabled(True)
    self.CnColorPushButton.setGeometry(qt.QRect(87, 333, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CnColorPushButton.sizePolicy().hasHeightForWidth())
    self.CnColorPushButton.setSizePolicy(sizePolicy)
    self.CnColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CnColorPushButton.setObjectName(("CnColorPushButton"))
    self.CoRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.CoRadioButton.setEnabled(True)
    self.CoRadioButton.setGeometry(qt.QRect(96, 298, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CoRadioButton.sizePolicy().hasHeightForWidth())
    self.CoRadioButton.setSizePolicy(sizePolicy)
    self.CoRadioButton.setText((""))
    self.CoRadioButton.setAutoExclusive(False)
    self.CoRadioButton.setObjectName(("CoRadioButton"))
    self.CoColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.CoColorPushButton.setEnabled(True)
    self.CoColorPushButton.setGeometry(qt.QRect(93, 277, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.CoColorPushButton.sizePolicy().hasHeightForWidth())
    self.CoColorPushButton.setSizePolicy(sizePolicy)
    self.CoColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.CoColorPushButton.setObjectName(("CoColorPushButton"))
    self.BaRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BaRadioButton.setEnabled(True)
    self.BaRadioButton.setGeometry(qt.QRect(273, 242, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BaRadioButton.sizePolicy().hasHeightForWidth())
    self.BaRadioButton.setSizePolicy(sizePolicy)
    self.BaRadioButton.setText((""))
    self.BaRadioButton.setAutoExclusive(False)
    self.BaRadioButton.setObjectName(("BaRadioButton"))
    self.BaColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BaColorPushButton.setEnabled(True)
    self.BaColorPushButton.setGeometry(qt.QRect(270, 222, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BaColorPushButton.sizePolicy().hasHeightForWidth())
    self.BaColorPushButton.setSizePolicy(sizePolicy)
    self.BaColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BaColorPushButton.setObjectName(("BaColorPushButton"))
    self.BbColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BbColorPushButton.setEnabled(True)
    self.BbColorPushButton.setGeometry(qt.QRect(330, 237, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BbColorPushButton.sizePolicy().hasHeightForWidth())
    self.BbColorPushButton.setSizePolicy(sizePolicy)
    self.BbColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BbColorPushButton.setObjectName(("BbColorPushButton"))
    self.BbRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BbRadioButton.setEnabled(True)
    self.BbRadioButton.setGeometry(qt.QRect(333, 256, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BbRadioButton.sizePolicy().hasHeightForWidth())
    self.BbRadioButton.setSizePolicy(sizePolicy)
    self.BbRadioButton.setText((""))
    self.BbRadioButton.setAutoExclusive(False)
    self.BbRadioButton.setObjectName(("BbRadioButton"))
    self.BcColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BcColorPushButton.setEnabled(True)
    self.BcColorPushButton.setGeometry(qt.QRect(369, 279, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BcColorPushButton.sizePolicy().hasHeightForWidth())
    self.BcColorPushButton.setSizePolicy(sizePolicy)
    self.BcColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BcColorPushButton.setObjectName(("BcColorPushButton"))
    self.BcRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BcRadioButton.setEnabled(True)
    self.BcRadioButton.setGeometry(qt.QRect(375, 301, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BcRadioButton.sizePolicy().hasHeightForWidth())
    self.BcRadioButton.setSizePolicy(sizePolicy)
    self.BcRadioButton.setText((""))
    self.BcRadioButton.setAutoExclusive(False)
    self.BcRadioButton.setObjectName(("BcRadioButton"))
    self.BdColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BdColorPushButton.setEnabled(True)
    self.BdColorPushButton.setGeometry(qt.QRect(393, 336, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BdColorPushButton.sizePolicy().hasHeightForWidth())
    self.BdColorPushButton.setSizePolicy(sizePolicy)
    self.BdColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BdColorPushButton.setObjectName(("BdColorPushButton"))
    self.BdRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BdRadioButton.setEnabled(True)
    self.BdRadioButton.setGeometry(qt.QRect(393, 358, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BdRadioButton.sizePolicy().hasHeightForWidth())
    self.BdRadioButton.setSizePolicy(sizePolicy)
    self.BdRadioButton.setText((""))
    self.BdRadioButton.setAutoExclusive(False)
    self.BdRadioButton.setObjectName(("BdRadioButton"))
    self.BeColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BeColorPushButton.setEnabled(True)
    self.BeColorPushButton.setGeometry(qt.QRect(372, 396, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BeColorPushButton.sizePolicy().hasHeightForWidth())
    self.BeColorPushButton.setSizePolicy(sizePolicy)
    self.BeColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BeColorPushButton.setObjectName(("BeColorPushButton"))
    self.BeRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BeRadioButton.setEnabled(True)
    self.BeRadioButton.setGeometry(qt.QRect(375, 418, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BeRadioButton.sizePolicy().hasHeightForWidth())
    self.BeRadioButton.setSizePolicy(sizePolicy)
    self.BeRadioButton.setText((""))
    self.BeRadioButton.setAutoExclusive(False)
    self.BeRadioButton.setObjectName(("BeRadioButton"))
    self.BfColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BfColorPushButton.setEnabled(True)
    self.BfColorPushButton.setGeometry(qt.QRect(327, 441, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BfColorPushButton.sizePolicy().hasHeightForWidth())
    self.BfColorPushButton.setSizePolicy(sizePolicy)
    self.BfColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BfColorPushButton.setObjectName(("BfColorPushButton"))
    self.BfRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BfRadioButton.setEnabled(True)
    self.BfRadioButton.setGeometry(qt.QRect(330, 460, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BfRadioButton.sizePolicy().hasHeightForWidth())
    self.BfRadioButton.setSizePolicy(sizePolicy)
    self.BfRadioButton.setText((""))
    self.BfRadioButton.setAutoExclusive(False)
    self.BfRadioButton.setObjectName(("BfRadioButton"))
    self.BgColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BgColorPushButton.setEnabled(True)
    self.BgColorPushButton.setGeometry(qt.QRect(264, 459, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BgColorPushButton.sizePolicy().hasHeightForWidth())
    self.BgColorPushButton.setSizePolicy(sizePolicy)
    self.BgColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BgColorPushButton.setObjectName(("BgColorPushButton"))
    self.BgRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BgRadioButton.setEnabled(True)
    self.BgRadioButton.setGeometry(qt.QRect(270, 478, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BgRadioButton.sizePolicy().hasHeightForWidth())
    self.BgRadioButton.setSizePolicy(sizePolicy)
    self.BgRadioButton.setText((""))
    self.BgRadioButton.setAutoExclusive(False)
    self.BgRadioButton.setObjectName(("BgRadioButton"))
    self.BhColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BhColorPushButton.setEnabled(True)
    self.BhColorPushButton.setGeometry(qt.QRect(204, 441, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BhColorPushButton.sizePolicy().hasHeightForWidth())
    self.BhColorPushButton.setSizePolicy(sizePolicy)
    self.BhColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BhColorPushButton.setObjectName(("BhColorPushButton"))
    self.BhRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BhRadioButton.setEnabled(True)
    self.BhRadioButton.setGeometry(qt.QRect(210, 463, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BhRadioButton.sizePolicy().hasHeightForWidth())
    self.BhRadioButton.setSizePolicy(sizePolicy)
    self.BhRadioButton.setText((""))
    self.BhRadioButton.setAutoExclusive(False)
    self.BhRadioButton.setObjectName(("BhRadioButton"))
    self.BiColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BiColorPushButton.setEnabled(True)
    self.BiColorPushButton.setGeometry(qt.QRect(165, 399, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BiColorPushButton.sizePolicy().hasHeightForWidth())
    self.BiColorPushButton.setSizePolicy(sizePolicy)
    self.BiColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BiColorPushButton.setObjectName(("BiColorPushButton"))
    self.BiRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BiRadioButton.setEnabled(True)
    self.BiRadioButton.setGeometry(qt.QRect(165, 418, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BiRadioButton.sizePolicy().hasHeightForWidth())
    self.BiRadioButton.setSizePolicy(sizePolicy)
    self.BiRadioButton.setText((""))
    self.BiRadioButton.setAutoExclusive(False)
    self.BiRadioButton.setObjectName(("BiRadioButton"))
    self.BjColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BjColorPushButton.setEnabled(True)
    self.BjColorPushButton.setGeometry(qt.QRect(138, 336, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BjColorPushButton.sizePolicy().hasHeightForWidth())
    self.BjColorPushButton.setSizePolicy(sizePolicy)
    self.BjColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BjColorPushButton.setObjectName(("BjColorPushButton"))
    self.BjRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BjRadioButton.setEnabled(True)
    self.BjRadioButton.setGeometry(qt.QRect(147, 360, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BjRadioButton.sizePolicy().hasHeightForWidth())
    self.BjRadioButton.setSizePolicy(sizePolicy)
    self.BjRadioButton.setText((""))
    self.BjRadioButton.setAutoExclusive(False)
    self.BjRadioButton.setObjectName(("BjRadioButton"))
    self.BkColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BkColorPushButton.setEnabled(True)
    self.BkColorPushButton.setGeometry(qt.QRect(162, 279, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BkColorPushButton.sizePolicy().hasHeightForWidth())
    self.BkColorPushButton.setSizePolicy(sizePolicy)
    self.BkColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BkColorPushButton.setObjectName(("BkColorPushButton"))
    self.BkRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BkRadioButton.setEnabled(True)
    self.BkRadioButton.setGeometry(qt.QRect(162, 301, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BkRadioButton.sizePolicy().hasHeightForWidth())
    self.BkRadioButton.setSizePolicy(sizePolicy)
    self.BkRadioButton.setText((""))
    self.BkRadioButton.setAutoExclusive(False)
    self.BkRadioButton.setObjectName(("BkRadioButton"))
    self.BlColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.BlColorPushButton.setEnabled(True)
    self.BlColorPushButton.setGeometry(qt.QRect(204, 237, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BlColorPushButton.sizePolicy().hasHeightForWidth())
    self.BlColorPushButton.setSizePolicy(sizePolicy)
    self.BlColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.BlColorPushButton.setObjectName(("BlColorPushButton"))
    self.BlRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.BlRadioButton.setEnabled(True)
    self.BlRadioButton.setGeometry(qt.QRect(210, 259, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.BlRadioButton.sizePolicy().hasHeightForWidth())
    self.BlRadioButton.setSizePolicy(sizePolicy)
    self.BlRadioButton.setText((""))
    self.BlRadioButton.setAutoExclusive(False)
    self.BlRadioButton.setObjectName(("BlRadioButton"))
    self.AaColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.AaColorPushButton.setEnabled(True)
    self.AaColorPushButton.setGeometry(qt.QRect(306, 279, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AaColorPushButton.sizePolicy().hasHeightForWidth())
    self.AaColorPushButton.setSizePolicy(sizePolicy)
    self.AaColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.AaColorPushButton.setObjectName(("AaColorPushButton"))
    self.AaRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.AaRadioButton.setEnabled(True)
    self.AaRadioButton.setGeometry(qt.QRect(306, 304, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AaRadioButton.sizePolicy().hasHeightForWidth())
    self.AaRadioButton.setSizePolicy(sizePolicy)
    self.AaRadioButton.setText((""))
    self.AaRadioButton.setAutoExclusive(False)
    self.AaRadioButton.setObjectName(("AaRadioButton"))
    self.AbColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.AbColorPushButton.setEnabled(True)
    self.AbColorPushButton.setGeometry(qt.QRect(333, 336, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AbColorPushButton.sizePolicy().hasHeightForWidth())
    self.AbColorPushButton.setSizePolicy(sizePolicy)
    self.AbColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.AbColorPushButton.setObjectName(("AbColorPushButton"))
    self.AbRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.AbRadioButton.setEnabled(True)
    self.AbRadioButton.setGeometry(qt.QRect(336, 361, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AbRadioButton.sizePolicy().hasHeightForWidth())
    self.AbRadioButton.setSizePolicy(sizePolicy)
    self.AbRadioButton.setText((""))
    self.AbRadioButton.setAutoExclusive(False)
    self.AbRadioButton.setObjectName(("AbRadioButton"))
    self.AcColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.AcColorPushButton.setEnabled(True)
    self.AcColorPushButton.setGeometry(qt.QRect(300, 399, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AcColorPushButton.sizePolicy().hasHeightForWidth())
    self.AcColorPushButton.setSizePolicy(sizePolicy)
    self.AcColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.AcColorPushButton.setObjectName(("AcColorPushButton"))
    self.AcRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.AcRadioButton.setEnabled(True)
    self.AcRadioButton.setGeometry(qt.QRect(299, 418, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AcRadioButton.sizePolicy().hasHeightForWidth())
    self.AcRadioButton.setSizePolicy(sizePolicy)
    self.AcRadioButton.setText((""))
    self.AcRadioButton.setAutoExclusive(False)
    self.AcRadioButton.setObjectName(("AcRadioButton"))
    self.AdColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.AdColorPushButton.setEnabled(True)
    self.AdColorPushButton.setGeometry(qt.QRect(243, 399, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AdColorPushButton.sizePolicy().hasHeightForWidth())
    self.AdColorPushButton.setSizePolicy(sizePolicy)
    self.AdColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.AdColorPushButton.setObjectName(("AdColorPushButton"))
    self.AdRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.AdRadioButton.setEnabled(True)
    self.AdRadioButton.setGeometry(qt.QRect(239, 415, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AdRadioButton.sizePolicy().hasHeightForWidth())
    self.AdRadioButton.setSizePolicy(sizePolicy)
    self.AdRadioButton.setText((""))
    self.AdRadioButton.setAutoExclusive(False)
    self.AdRadioButton.setObjectName(("AdRadioButton"))
    self.AeColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.AeColorPushButton.setEnabled(True)
    self.AeColorPushButton.setGeometry(qt.QRect(204, 336, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AeColorPushButton.sizePolicy().hasHeightForWidth())
    self.AeColorPushButton.setSizePolicy(sizePolicy)
    self.AeColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.AeColorPushButton.setObjectName(("AeColorPushButton"))
    self.AeRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.AeRadioButton.setEnabled(True)
    self.AeRadioButton.setGeometry(qt.QRect(206, 363, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AeRadioButton.sizePolicy().hasHeightForWidth())
    self.AeRadioButton.setSizePolicy(sizePolicy)
    self.AeRadioButton.setText((""))
    self.AeRadioButton.setAutoExclusive(False)
    self.AeRadioButton.setObjectName(("AeRadioButton"))
    self.AfColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.AfColorPushButton.setEnabled(True)
    self.AfColorPushButton.setGeometry(qt.QRect(243, 279, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AfColorPushButton.sizePolicy().hasHeightForWidth())
    self.AfColorPushButton.setSizePolicy(sizePolicy)
    self.AfColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.AfColorPushButton.setObjectName(("AfColorPushButton"))
    self.AfRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.AfRadioButton.setEnabled(True)
    self.AfRadioButton.setGeometry(qt.QRect(239, 304, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.AfRadioButton.sizePolicy().hasHeightForWidth())
    self.AfRadioButton.setSizePolicy(sizePolicy)
    self.AfRadioButton.setText((""))
    self.AfRadioButton.setAutoExclusive(False)
    self.AfRadioButton.setObjectName(("AfRadioButton"))
    self.IuColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.IuColorPushButton.setEnabled(True)
    self.IuColorPushButton.setGeometry(qt.QRect(273, 333, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.IuColorPushButton.sizePolicy().hasHeightForWidth())
    self.IuColorPushButton.setSizePolicy(sizePolicy)
    self.IuColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.IuColorPushButton.setObjectName(("IuColorPushButton"))
    self.IuRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.IuRadioButton.setEnabled(True)
    self.IuRadioButton.setGeometry(qt.QRect(269, 358, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.IuRadioButton.sizePolicy().hasHeightForWidth())
    self.IuRadioButton.setSizePolicy(sizePolicy)
    self.IuRadioButton.setText((""))
    self.IuRadioButton.setAutoExclusive(False)
    self.IuRadioButton.setObjectName(("IuRadioButton"))
    self.DaColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DaColorPushButton.setEnabled(True)
    self.DaColorPushButton.setGeometry(qt.QRect(264, 99, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DaColorPushButton.sizePolicy().hasHeightForWidth())
    self.DaColorPushButton.setSizePolicy(sizePolicy)
    self.DaColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DaColorPushButton.setObjectName(("DaColorPushButton"))
    self.DaRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DaRadioButton.setEnabled(True)
    self.DaRadioButton.setGeometry(qt.QRect(269, 124, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DaRadioButton.sizePolicy().hasHeightForWidth())
    self.DaRadioButton.setSizePolicy(sizePolicy)
    self.DaRadioButton.setText((""))
    self.DaRadioButton.setAutoExclusive(False)
    self.DaRadioButton.setObjectName(("DaRadioButton"))
    self.DbColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DbColorPushButton.setEnabled(True)
    self.DbColorPushButton.setGeometry(qt.QRect(330, 111, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DbColorPushButton.sizePolicy().hasHeightForWidth())
    self.DbColorPushButton.setSizePolicy(sizePolicy)
    self.DbColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DbColorPushButton.setObjectName(("DbColorPushButton"))
    self.DbRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DbRadioButton.setEnabled(True)
    self.DbRadioButton.setGeometry(qt.QRect(332, 133, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DbRadioButton.sizePolicy().hasHeightForWidth())
    self.DbRadioButton.setSizePolicy(sizePolicy)
    self.DbRadioButton.setText((""))
    self.DbRadioButton.setAutoExclusive(False)
    self.DbRadioButton.setObjectName(("DbRadioButton"))
    self.DcColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DcColorPushButton.setEnabled(True)
    self.DcColorPushButton.setGeometry(qt.QRect(390, 129, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DcColorPushButton.sizePolicy().hasHeightForWidth())
    self.DcColorPushButton.setSizePolicy(sizePolicy)
    self.DcColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DcColorPushButton.setObjectName(("DcColorPushButton"))
    self.DcRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DcRadioButton.setEnabled(True)
    self.DcRadioButton.setGeometry(qt.QRect(392, 154, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DcRadioButton.sizePolicy().hasHeightForWidth())
    self.DcRadioButton.setSizePolicy(sizePolicy)
    self.DcRadioButton.setText((""))
    self.DcRadioButton.setAutoExclusive(False)
    self.DcRadioButton.setObjectName(("DcRadioButton"))
    self.DdColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DdColorPushButton.setEnabled(True)
    self.DdColorPushButton.setGeometry(qt.QRect(393, 537, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DdColorPushButton.sizePolicy().hasHeightForWidth())
    self.DdColorPushButton.setSizePolicy(sizePolicy)
    self.DdColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DdColorPushButton.setObjectName(("DdColorPushButton"))
    self.DdRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DdRadioButton.setEnabled(True)
    self.DdRadioButton.setGeometry(qt.QRect(392, 562, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DdRadioButton.sizePolicy().hasHeightForWidth())
    self.DdRadioButton.setSizePolicy(sizePolicy)
    self.DdRadioButton.setText((""))
    self.DdRadioButton.setAutoExclusive(False)
    self.DdRadioButton.setObjectName(("DdRadioButton"))
    self.DeColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DeColorPushButton.setEnabled(True)
    self.DeColorPushButton.setGeometry(qt.QRect(333, 567, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DeColorPushButton.sizePolicy().hasHeightForWidth())
    self.DeColorPushButton.setSizePolicy(sizePolicy)
    self.DeColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DeColorPushButton.setObjectName(("DeColorPushButton"))
    self.DeRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DeRadioButton.setEnabled(True)
    self.DeRadioButton.setGeometry(qt.QRect(335, 586, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DeRadioButton.sizePolicy().hasHeightForWidth())
    self.DeRadioButton.setSizePolicy(sizePolicy)
    self.DeRadioButton.setText((""))
    self.DeRadioButton.setAutoExclusive(False)
    self.DeRadioButton.setObjectName(("DeRadioButton"))
    self.DfColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DfColorPushButton.setEnabled(True)
    self.DfColorPushButton.setGeometry(qt.QRect(267, 579, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DfColorPushButton.sizePolicy().hasHeightForWidth())
    self.DfColorPushButton.setSizePolicy(sizePolicy)
    self.DfColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DfColorPushButton.setObjectName(("DfColorPushButton"))
    self.DfRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DfRadioButton.setEnabled(True)
    self.DfRadioButton.setGeometry(qt.QRect(269, 598, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DfRadioButton.sizePolicy().hasHeightForWidth())
    self.DfRadioButton.setSizePolicy(sizePolicy)
    self.DfRadioButton.setText((""))
    self.DfRadioButton.setAutoExclusive(False)
    self.DfRadioButton.setObjectName(("DfRadioButton"))
    self.DgColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DgColorPushButton.setEnabled(True)
    self.DgColorPushButton.setGeometry(qt.QRect(204, 567, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DgColorPushButton.sizePolicy().hasHeightForWidth())
    self.DgColorPushButton.setSizePolicy(sizePolicy)
    self.DgColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DgColorPushButton.setObjectName(("DgColorPushButton"))
    self.DgRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DgRadioButton.setEnabled(True)
    self.DgRadioButton.setGeometry(qt.QRect(206, 589, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DgRadioButton.sizePolicy().hasHeightForWidth())
    self.DgRadioButton.setSizePolicy(sizePolicy)
    self.DgRadioButton.setText((""))
    self.DgRadioButton.setAutoExclusive(False)
    self.DgRadioButton.setObjectName(("DgRadioButton"))
    self.DhColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DhColorPushButton.setEnabled(True)
    self.DhColorPushButton.setGeometry(qt.QRect(144, 540, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DhColorPushButton.sizePolicy().hasHeightForWidth())
    self.DhColorPushButton.setSizePolicy(sizePolicy)
    self.DhColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DhColorPushButton.setObjectName(("DhColorPushButton"))
    self.DhRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DhRadioButton.setEnabled(True)
    self.DhRadioButton.setGeometry(qt.QRect(146, 565, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DhRadioButton.sizePolicy().hasHeightForWidth())
    self.DhRadioButton.setSizePolicy(sizePolicy)
    self.DhRadioButton.setText((""))
    self.DhRadioButton.setAutoExclusive(False)
    self.DhRadioButton.setObjectName(("DhRadioButton"))
    self.DiColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DiColorPushButton.setEnabled(True)
    self.DiColorPushButton.setGeometry(qt.QRect(144, 138, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DiColorPushButton.sizePolicy().hasHeightForWidth())
    self.DiColorPushButton.setSizePolicy(sizePolicy)
    self.DiColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DiColorPushButton.setObjectName(("DiColorPushButton"))
    self.DiRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DiRadioButton.setEnabled(True)
    self.DiRadioButton.setGeometry(qt.QRect(146, 157, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DiRadioButton.sizePolicy().hasHeightForWidth())
    self.DiRadioButton.setSizePolicy(sizePolicy)
    self.DiRadioButton.setText((""))
    self.DiRadioButton.setAutoExclusive(False)
    self.DiRadioButton.setObjectName(("DiRadioButton"))
    self.DjColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.DjColorPushButton.setEnabled(True)
    self.DjColorPushButton.setGeometry(qt.QRect(201, 114, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DjColorPushButton.sizePolicy().hasHeightForWidth())
    self.DjColorPushButton.setSizePolicy(sizePolicy)
    self.DjColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.DjColorPushButton.setObjectName(("DjColorPushButton"))
    self.DjRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.DjRadioButton.setEnabled(True)
    self.DjRadioButton.setGeometry(qt.QRect(206, 133, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.DjRadioButton.sizePolicy().hasHeightForWidth())
    self.DjRadioButton.setSizePolicy(sizePolicy)
    self.DjRadioButton.setText((""))
    self.DjRadioButton.setAutoExclusive(False)
    self.DjRadioButton.setObjectName(("DjRadioButton"))
    self.EaColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.EaColorPushButton.setEnabled(True)
    self.EaColorPushButton.setGeometry(qt.QRect(294, 48, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EaColorPushButton.sizePolicy().hasHeightForWidth())
    self.EaColorPushButton.setSizePolicy(sizePolicy)
    self.EaColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.EaColorPushButton.setObjectName(("EaColorPushButton"))
    self.EaRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.EaRadioButton.setEnabled(True)
    self.EaRadioButton.setGeometry(qt.QRect(297, 69, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EaRadioButton.sizePolicy().hasHeightForWidth())
    self.EaRadioButton.setSizePolicy(sizePolicy)
    self.EaRadioButton.setText((""))
    self.EaRadioButton.setAutoExclusive(False)
    self.EaRadioButton.setObjectName(("EaRadioButton"))
    self.EbRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.EbRadioButton.setEnabled(True)
    self.EbRadioButton.setGeometry(qt.QRect(348, 77, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EbRadioButton.sizePolicy().hasHeightForWidth())
    self.EbRadioButton.setSizePolicy(sizePolicy)
    self.EbRadioButton.setText((""))
    self.EbRadioButton.setAutoExclusive(False)
    self.EbRadioButton.setObjectName(("EbRadioButton"))
    self.EbColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.EbColorPushButton.setEnabled(True)
    self.EbColorPushButton.setGeometry(qt.QRect(348, 58, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EbColorPushButton.sizePolicy().hasHeightForWidth())
    self.EbColorPushButton.setSizePolicy(sizePolicy)
    self.EbColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.EbColorPushButton.setObjectName(("EbColorPushButton"))
    self.EcRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.EcRadioButton.setEnabled(True)
    self.EcRadioButton.setGeometry(qt.QRect(350, 643, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EcRadioButton.sizePolicy().hasHeightForWidth())
    self.EcRadioButton.setSizePolicy(sizePolicy)
    self.EcRadioButton.setText((""))
    self.EcRadioButton.setAutoExclusive(False)
    self.EcRadioButton.setObjectName(("EcRadioButton"))
    self.EcColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.EcColorPushButton.setEnabled(True)
    self.EcColorPushButton.setGeometry(qt.QRect(348, 624, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EcColorPushButton.sizePolicy().hasHeightForWidth())
    self.EcColorPushButton.setSizePolicy(sizePolicy)
    self.EcColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.EcColorPushButton.setObjectName(("EcColorPushButton"))
    self.EdRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.EdRadioButton.setEnabled(True)
    self.EdRadioButton.setGeometry(qt.QRect(296, 653, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EdRadioButton.sizePolicy().hasHeightForWidth())
    self.EdRadioButton.setSizePolicy(sizePolicy)
    self.EdRadioButton.setText((""))
    self.EdRadioButton.setAutoExclusive(False)
    self.EdRadioButton.setObjectName(("EdRadioButton"))
    self.EdColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.EdColorPushButton.setEnabled(True)
    self.EdColorPushButton.setGeometry(qt.QRect(294, 633, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EdColorPushButton.sizePolicy().hasHeightForWidth())
    self.EdColorPushButton.setSizePolicy(sizePolicy)
    self.EdColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.EdColorPushButton.setObjectName(("EdColorPushButton"))
    self.EeRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.EeRadioButton.setEnabled(True)
    self.EeRadioButton.setGeometry(qt.QRect(245, 653, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EeRadioButton.sizePolicy().hasHeightForWidth())
    self.EeRadioButton.setSizePolicy(sizePolicy)
    self.EeRadioButton.setText((""))
    self.EeRadioButton.setAutoExclusive(False)
    self.EeRadioButton.setObjectName(("EeRadioButton"))
    self.EeColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.EeColorPushButton.setEnabled(True)
    self.EeColorPushButton.setGeometry(qt.QRect(243, 633, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EeColorPushButton.sizePolicy().hasHeightForWidth())
    self.EeColorPushButton.setSizePolicy(sizePolicy)
    self.EeColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.EeColorPushButton.setObjectName(("EeColorPushButton"))
    self.EfRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.EfRadioButton.setEnabled(True)
    self.EfRadioButton.setGeometry(qt.QRect(191, 644, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EfRadioButton.sizePolicy().hasHeightForWidth())
    self.EfRadioButton.setSizePolicy(sizePolicy)
    self.EfRadioButton.setText((""))
    self.EfRadioButton.setAutoExclusive(False)
    self.EfRadioButton.setObjectName(("EfRadioButton"))
    self.EfColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.EfColorPushButton.setEnabled(True)
    self.EfColorPushButton.setGeometry(qt.QRect(186, 624, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EfColorPushButton.sizePolicy().hasHeightForWidth())
    self.EfColorPushButton.setSizePolicy(sizePolicy)
    self.EfColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.EfColorPushButton.setObjectName(("EfColorPushButton"))
    self.EgRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.EgRadioButton.setEnabled(True)
    self.EgRadioButton.setGeometry(qt.QRect(192, 77, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EgRadioButton.sizePolicy().hasHeightForWidth())
    self.EgRadioButton.setSizePolicy(sizePolicy)
    self.EgRadioButton.setText((""))
    self.EgRadioButton.setAutoExclusive(False)
    self.EgRadioButton.setObjectName(("EgRadioButton"))
    self.EgColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.EgColorPushButton.setEnabled(True)
    self.EgColorPushButton.setGeometry(qt.QRect(186, 58, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EgColorPushButton.sizePolicy().hasHeightForWidth())
    self.EgColorPushButton.setSizePolicy(sizePolicy)
    self.EgColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.EgColorPushButton.setObjectName(("EgColorPushButton"))
    self.EhRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.EhRadioButton.setEnabled(True)
    self.EhRadioButton.setGeometry(qt.QRect(242, 68, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EhRadioButton.sizePolicy().hasHeightForWidth())
    self.EhRadioButton.setSizePolicy(sizePolicy)
    self.EhRadioButton.setText((""))
    self.EhRadioButton.setAutoExclusive(False)
    self.EhRadioButton.setObjectName(("EhRadioButton"))
    self.EhColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.EhColorPushButton.setEnabled(True)
    self.EhColorPushButton.setGeometry(qt.QRect(237, 48, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.EhColorPushButton.sizePolicy().hasHeightForWidth())
    self.EhColorPushButton.setSizePolicy(sizePolicy)
    self.EhColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.EhColorPushButton.setObjectName(("EhColorPushButton"))
    self.FaRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.FaRadioButton.setEnabled(True)
    self.FaRadioButton.setGeometry(qt.QRect(437, 125, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FaRadioButton.sizePolicy().hasHeightForWidth())
    self.FaRadioButton.setSizePolicy(sizePolicy)
    self.FaRadioButton.setText((""))
    self.FaRadioButton.setAutoExclusive(False)
    self.FaRadioButton.setObjectName(("FaRadioButton"))
    self.FaColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.FaColorPushButton.setEnabled(True)
    self.FaColorPushButton.setGeometry(qt.QRect(435, 102, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FaColorPushButton.sizePolicy().hasHeightForWidth())
    self.FaColorPushButton.setSizePolicy(sizePolicy)
    self.FaColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.FaColorPushButton.setObjectName(("FaColorPushButton"))
    self.FbRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.FbRadioButton.setEnabled(True)
    self.FbRadioButton.setGeometry(qt.QRect(455, 152, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FbRadioButton.sizePolicy().hasHeightForWidth())
    self.FbRadioButton.setSizePolicy(sizePolicy)
    self.FbRadioButton.setText((""))
    self.FbRadioButton.setAutoExclusive(False)
    self.FbRadioButton.setObjectName(("FbRadioButton"))
    self.FbColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.FbColorPushButton.setEnabled(True)
    self.FbColorPushButton.setGeometry(qt.QRect(456, 129, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FbColorPushButton.sizePolicy().hasHeightForWidth())
    self.FbColorPushButton.setSizePolicy(sizePolicy)
    self.FbColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.FbColorPushButton.setObjectName(("FbColorPushButton"))
    self.FhRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.FhRadioButton.setEnabled(True)
    self.FhRadioButton.setGeometry(qt.QRect(105, 128, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FhRadioButton.sizePolicy().hasHeightForWidth())
    self.FhRadioButton.setSizePolicy(sizePolicy)
    self.FhRadioButton.setText((""))
    self.FhRadioButton.setAutoExclusive(False)
    self.FhRadioButton.setObjectName(("FhRadioButton"))
    self.FhColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.FhColorPushButton.setEnabled(True)
    self.FhColorPushButton.setGeometry(qt.QRect(102, 109, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FhColorPushButton.sizePolicy().hasHeightForWidth())
    self.FhColorPushButton.setSizePolicy(sizePolicy)
    self.FhColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.FhColorPushButton.setObjectName(("FhColorPushButton"))
    self.FgRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.FgRadioButton.setEnabled(True)
    self.FgRadioButton.setGeometry(qt.QRect(84, 158, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FgRadioButton.sizePolicy().hasHeightForWidth())
    self.FgRadioButton.setSizePolicy(sizePolicy)
    self.FgRadioButton.setText((""))
    self.FgRadioButton.setAutoExclusive(False)
    self.FgRadioButton.setObjectName(("FgRadioButton"))
    self.FgColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.FgColorPushButton.setEnabled(True)
    self.FgColorPushButton.setGeometry(qt.QRect(81, 141, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FgColorPushButton.sizePolicy().hasHeightForWidth())
    self.FgColorPushButton.setSizePolicy(sizePolicy)
    self.FgColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.FgColorPushButton.setObjectName(("FgColorPushButton"))
    self.FcRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.FcRadioButton.setEnabled(True)
    self.FcRadioButton.setGeometry(qt.QRect(458, 566, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FcRadioButton.sizePolicy().hasHeightForWidth())
    self.FcRadioButton.setSizePolicy(sizePolicy)
    self.FcRadioButton.setText((""))
    self.FcRadioButton.setAutoExclusive(False)
    self.FcRadioButton.setObjectName(("FcRadioButton"))
    self.FcColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.FcColorPushButton.setEnabled(True)
    self.FcColorPushButton.setGeometry(qt.QRect(456, 543, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FcColorPushButton.sizePolicy().hasHeightForWidth())
    self.FcColorPushButton.setSizePolicy(sizePolicy)
    self.FcColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.FcColorPushButton.setObjectName(("FcColorPushButton"))
    self.FdRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.FdRadioButton.setEnabled(True)
    self.FdRadioButton.setGeometry(qt.QRect(437, 593, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FdRadioButton.sizePolicy().hasHeightForWidth())
    self.FdRadioButton.setSizePolicy(sizePolicy)
    self.FdRadioButton.setText((""))
    self.FdRadioButton.setAutoExclusive(False)
    self.FdRadioButton.setObjectName(("FdRadioButton"))
    self.FdColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.FdColorPushButton.setEnabled(True)
    self.FdColorPushButton.setGeometry(qt.QRect(432, 576, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FdColorPushButton.sizePolicy().hasHeightForWidth())
    self.FdColorPushButton.setSizePolicy(sizePolicy)
    self.FdColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.FdColorPushButton.setObjectName(("FdColorPushButton"))
    self.FeRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.FeRadioButton.setEnabled(True)
    self.FeRadioButton.setGeometry(qt.QRect(107, 596, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FeRadioButton.sizePolicy().hasHeightForWidth())
    self.FeRadioButton.setSizePolicy(sizePolicy)
    self.FeRadioButton.setText((""))
    self.FeRadioButton.setAutoExclusive(False)
    self.FeRadioButton.setObjectName(("FeRadioButton"))
    self.FeColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.FeColorPushButton.setEnabled(True)
    self.FeColorPushButton.setGeometry(qt.QRect(105, 573, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FeColorPushButton.sizePolicy().hasHeightForWidth())
    self.FeColorPushButton.setSizePolicy(sizePolicy)
    self.FeColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.FeColorPushButton.setObjectName(("FeColorPushButton"))
    self.FfRadioButton = qt.QRadioButton(TemplateSheetWidget)
    self.FfRadioButton.setEnabled(True)
    self.FfRadioButton.setGeometry(qt.QRect(83, 565, 24, 16))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FfRadioButton.sizePolicy().hasHeightForWidth())
    self.FfRadioButton.setSizePolicy(sizePolicy)
    self.FfRadioButton.setText((""))
    self.FfRadioButton.setAutoExclusive(False)
    self.FfRadioButton.setObjectName(("FfRadioButton"))
    self.FfColorPushButton = qt.QPushButton(TemplateSheetWidget)
    self.FfColorPushButton.setEnabled(True)
    self.FfColorPushButton.setGeometry(qt.QRect(81, 540, 21, 21))
    sizePolicy = qt.QSizePolicy(qt.QSizePolicy.Minimum, qt.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.FfColorPushButton.sizePolicy().hasHeightForWidth())
    self.FfColorPushButton.setSizePolicy(sizePolicy)
    self.FfColorPushButton.setStyleSheet(("background-color: rgb(0, 255, 0);"))
    self.FfColorPushButton.setObjectName(("FfColorPushButton"))
    self.RegistrationProcessingLabel = qt.QLabel(TemplateSheetWidget)
    self.RegistrationProcessingLabel.setEnabled(True)
    self.RegistrationProcessingLabel.setGeometry(qt.QRect(462, 60, 54, 12))
    self.RegistrationProcessingLabel.setText((""))
    self.RegistrationProcessingLabel.setObjectName(("RegistrationProcessingLabel"))

    self.retranslateUi(TemplateSheetWidget)
    qt.QMetaObject.connectSlotsByName(TemplateSheetWidget)

  def retranslateUi(self, TemplateSheetWidget):
    TemplateSheetWidget.setWindowTitle(qt.QApplication.translate("TemplateSheetWidget", "TemplateSheetWidget", None, qt.QApplication.UnicodeUTF8))
    self.CqColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cq", None, qt.QApplication.UnicodeUTF8))
    self.CpColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cp", None, qt.QApplication.UnicodeUTF8))
    self.CrColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cr", None, qt.QApplication.UnicodeUTF8))
    self.LoadTemplatePushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Load(Scene/Template)", None, qt.QApplication.UnicodeUTF8))
    self.AddVolumePushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "AddVolume", None, qt.QApplication.UnicodeUTF8))
    self.ShowNeedlesPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "ShowNeedles", None, qt.QApplication.UnicodeUTF8))
    self.SelectNeedlesPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "SelectNeedles", None, qt.QApplication.UnicodeUTF8))
    self.CADmodel2ImageRegPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "CADmodel2Image", None, qt.QApplication.UnicodeUTF8))
    self.CaColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ca", None, qt.QApplication.UnicodeUTF8))
    self.CbColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cb", None, qt.QApplication.UnicodeUTF8))
    self.CcColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cc", None, qt.QApplication.UnicodeUTF8))
    self.CdColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cd", None, qt.QApplication.UnicodeUTF8))
    self.CeColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ce", None, qt.QApplication.UnicodeUTF8))
    self.CfColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cf", None, qt.QApplication.UnicodeUTF8))
    self.CgColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cg", None, qt.QApplication.UnicodeUTF8))
    self.ChColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ch", None, qt.QApplication.UnicodeUTF8))
    self.CiColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ci", None, qt.QApplication.UnicodeUTF8))
    self.CjColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cj", None, qt.QApplication.UnicodeUTF8))
    self.CkColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ck", None, qt.QApplication.UnicodeUTF8))
    self.ClColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cl", None, qt.QApplication.UnicodeUTF8))
    self.CmColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cm", None, qt.QApplication.UnicodeUTF8))
    self.CnColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Cn", None, qt.QApplication.UnicodeUTF8))
    self.CoColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Co", None, qt.QApplication.UnicodeUTF8))
    self.BaColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ba", None, qt.QApplication.UnicodeUTF8))
    self.BbColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bb", None, qt.QApplication.UnicodeUTF8))
    self.BcColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bc", None, qt.QApplication.UnicodeUTF8))
    self.BdColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bd", None, qt.QApplication.UnicodeUTF8))
    self.BeColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Be", None, qt.QApplication.UnicodeUTF8))
    self.BfColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bf", None, qt.QApplication.UnicodeUTF8))
    self.BgColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bg", None, qt.QApplication.UnicodeUTF8))
    self.BhColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bh", None, qt.QApplication.UnicodeUTF8))
    self.BiColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bi", None, qt.QApplication.UnicodeUTF8))
    self.BjColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bj", None, qt.QApplication.UnicodeUTF8))
    self.BkColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bk", None, qt.QApplication.UnicodeUTF8))
    self.BlColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Bl", None, qt.QApplication.UnicodeUTF8))
    self.AaColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Aa", None, qt.QApplication.UnicodeUTF8))
    self.AbColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ab", None, qt.QApplication.UnicodeUTF8))
    self.AcColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ac", None, qt.QApplication.UnicodeUTF8))
    self.AdColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ad", None, qt.QApplication.UnicodeUTF8))
    self.AeColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ae", None, qt.QApplication.UnicodeUTF8))
    self.AfColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Af", None, qt.QApplication.UnicodeUTF8))
    self.IuColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Iu", None, qt.QApplication.UnicodeUTF8))
    self.DaColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Da", None, qt.QApplication.UnicodeUTF8))
    self.DbColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Db", None, qt.QApplication.UnicodeUTF8))
    self.DcColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Dc", None, qt.QApplication.UnicodeUTF8))
    self.DdColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Dd", None, qt.QApplication.UnicodeUTF8))
    self.DeColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "De", None, qt.QApplication.UnicodeUTF8))
    self.DfColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Df", None, qt.QApplication.UnicodeUTF8))
    self.DgColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Dg", None, qt.QApplication.UnicodeUTF8))
    self.DhColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Dh", None, qt.QApplication.UnicodeUTF8))
    self.DiColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Di", None, qt.QApplication.UnicodeUTF8))
    self.DjColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Dj", None, qt.QApplication.UnicodeUTF8))
    self.EaColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ea", None, qt.QApplication.UnicodeUTF8))
    self.EbColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Eb", None, qt.QApplication.UnicodeUTF8))
    self.EcColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ec", None, qt.QApplication.UnicodeUTF8))
    self.EdColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ed", None, qt.QApplication.UnicodeUTF8))
    self.EeColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ee", None, qt.QApplication.UnicodeUTF8))
    self.EfColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ef", None, qt.QApplication.UnicodeUTF8))
    self.EgColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Eg", None, qt.QApplication.UnicodeUTF8))
    self.EhColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Eh", None, qt.QApplication.UnicodeUTF8))
    self.FaColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Fa", None, qt.QApplication.UnicodeUTF8))
    self.FbColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Fb", None, qt.QApplication.UnicodeUTF8))
    self.FhColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Fh", None, qt.QApplication.UnicodeUTF8))
    self.FgColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Fg", None, qt.QApplication.UnicodeUTF8))
    self.FcColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Fc", None, qt.QApplication.UnicodeUTF8))
    self.FdColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Fd", None, qt.QApplication.UnicodeUTF8))
    self.FeColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Fe", None, qt.QApplication.UnicodeUTF8))
    self.FfColorPushButton.setText(qt.QApplication.translate("TemplateSheetWidget", "Ff", None, qt.QApplication.UnicodeUTF8))
